#! /usr/bin/perl

$file = $ARGV[0];
$source = $ARGV[1];
$dest = $ARGV[2];
$handover1 = $ARGV[3];
$handover2 = $ARGV[4];
$line = 0;
$source_pos= $source+0.1;
$dest_pos = $dest+0.1;

%node;
%time;

sub by_number{
	if($a<$b){-1}elsif($a>$b){1}else{0}
}


open (DATA,"<$file") or die "Cannot open $file:$!";

while (<DATA>){
	
	@x = split/\s+/;
	$line++;
	if ($x[2] eq $source && $x[0] eq '+' && $x[8] eq $source_pos && $x[9] eq $dest_pos){
		$node{$x[11]} = $x[1];
		$time{$x[11]} = $x[1];
		 $node{$x[11]}.=" nr";
	}
	if ($x[3] eq $dest && $x[0] eq 'r' && $x[8] eq $source_pos && $x[9] eq $dest_pos){
		if (exists $node{$x[11]}){
			$node{$x[11]} =~ s/\s+\w+//;
			$node{$x[11]} = $x[1] - $node{$x[11]};
		}
		else{
			print "error at $x[1] $line\n";
		}
	}
}

$i1=1,$i2=1,$i3=1;
$sum_b=0,$sum_m=0,$sum_a=0;
#$max=0;
#$min=2;
foreach (sort by_number keys %node){
	if (not $node{$_}=~ /nr/){
#		print "$i $node{$_} $time{$_} $_\n";
#		print "$_ $node{$_}\n";
#	print "$time{$_} $node{$_}\n" if(not $node{$_}=~ /nr/);
		if ($time{$_} <= $handover1){
			$i1++;
			$sum_b += $node{$_};
		}
		elsif($time{$_} <= $handover2){
			$i2++;
			$sum_m += $node{$_};
		}
		else{
			$i3++;
			$sum_a += $node{$_};
		}
	}
}	
print STDOUT "before $source $i1 $sum_b\nmiddle $source $i2 $sum_m\nafter $source $i3 $sum_a\n";
#print STDOUT "$file $source $dest:\nthe average delay is $avg_delay.\nthe maximum delay is $max and the minimum delay is $min.\n";

close DATA;

exit(0);
